// Preset definitions for all three models

export const presets = [
    // ── Gray-Scott ──────────────────────────────
    {
        name: 'Mitosis',
        model: 'gray-scott',
        params: { F: 0.028, k: 0.062, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'center-seed',
        display: 1,
        colormap: 'Viridis',
        displayRange: [0, 1],
        description: 'Self-replicating spots',
    },
    {
        name: 'Coral Growth',
        model: 'gray-scott',
        params: { F: 0.062, k: 0.063, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'center-seed',
        display: 1,
        colormap: 'Inferno',
        displayRange: [0, 1],
        description: 'Branching coral-like fingers',
    },
    {
        name: 'Maze',
        model: 'gray-scott',
        params: { F: 0.029, k: 0.057, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'center-seed',
        display: 1,
        colormap: 'Plasma',
        displayRange: [0, 1],
        description: 'Labyrinthine winding channels',
    },
    {
        name: 'Spots',
        model: 'gray-scott',
        params: { F: 0.035, k: 0.065, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'center-seed',
        display: 1,
        colormap: 'Viridis',
        displayRange: [0, 1],
        description: 'Stable spotted pattern',
    },
    {
        name: 'Stripes',
        model: 'gray-scott',
        params: { F: 0.04, k: 0.06, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'center-seed',
        display: 1,
        colormap: 'Magma',
        displayRange: [0, 1],
        description: 'Parallel stripe formation',
    },
    {
        name: 'Worms',
        model: 'gray-scott',
        params: { F: 0.078, k: 0.061, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'multi-seed',
        display: 1,
        colormap: 'Turbo',
        displayRange: [0, 1],
        description: 'Worm-like moving structures',
    },
    {
        name: 'Bubbles',
        model: 'gray-scott',
        params: { F: 0.012, k: 0.05, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'center-seed',
        display: 1,
        colormap: 'Inferno',
        displayRange: [0, 1],
        description: 'Expanding bubble fronts',
    },
    {
        name: 'Chaos',
        model: 'gray-scott',
        params: { F: 0.026, k: 0.051, Du: 0.21, Dv: 0.105, dt: 1.0 },
        init: 'multi-seed',
        display: 1,
        colormap: 'Plasma',
        displayRange: [0, 1],
        description: 'Turbulent, chaotic dynamics',
    },

    // ── FitzHugh-Nagumo ─────────────────────────
    {
        name: 'Spiral Waves',
        model: 'fitzhugh-nagumo',
        params: { Du: 0.2, Dv: 0.05, stimulus: 0.0, epsilon: 0.01, a1: 1.0, a0: 0.0, dt: 0.05 },
        init: 'multi-seed',
        display: 0,
        colormap: 'Plasma',
        displayRange: [-1.5, 1.5],
        description: 'Classic spiral wave formation',
    },
    {
        name: 'Labyrinth (FHN)',
        model: 'fitzhugh-nagumo',
        params: { Du: 0.2, Dv: 0.05, stimulus: 0.0, epsilon: 0.05, a1: 2.0, a0: 0.0, dt: 0.05 },
        init: 'random-noise',
        display: 0,
        colormap: 'Viridis',
        displayRange: [-1.5, 1.5],
        description: 'Static labyrinth pattern',
    },
    {
        name: 'Target Waves',
        model: 'fitzhugh-nagumo',
        params: { Du: 0.2, Dv: 0.05, stimulus: 0.1, epsilon: 0.01, a1: 1.0, a0: 0.0, dt: 0.05 },
        init: 'center-seed',
        display: 0,
        colormap: 'Turbo',
        displayRange: [-1.5, 1.5],
        description: 'Expanding concentric rings',
    },

    // ── Brusselator ─────────────────────────────
    {
        name: 'Hexagons',
        model: 'brusselator',
        params: { A_feed: 4.5, B_feed: 8.0, Du: 1.0, Dv: 8.0, dt: 0.01 },
        init: 'random-noise',
        display: 0,
        colormap: 'Turbo',
        displayRange: [0, 8],
        description: 'Honeycomb hex pattern',
    },
    {
        name: 'Brusselator Stripes',
        model: 'brusselator',
        params: { A_feed: 4.5, B_feed: 6.5, Du: 1.0, Dv: 8.0, dt: 0.01 },
        init: 'random-noise',
        display: 0,
        colormap: 'Magma',
        displayRange: [0, 8],
        description: 'Parallel stripe formation',
    },
    {
        name: 'Brusselator Spots',
        model: 'brusselator',
        params: { A_feed: 3.0, B_feed: 10.0, Du: 1.0, Dv: 8.0, dt: 0.01 },
        init: 'random-noise',
        display: 0,
        colormap: 'Inferno',
        displayRange: [0, 8],
        description: 'Isolated spot array',
    },
];

export function presetsByModel(modelName) {
    return presets.filter(p => p.model === modelName);
}
